require("nichtsam.colorscheme")
require("nichtsam.options")
require("nichtsam.keymaps")
require("nichtsam.packer")
require("nichtsam.cmp")
require("nichtsam.mason")
require("nichtsam.telescope")
require("nichtsam.treesitter")
require("nichtsam.autopairs")
require("nichtsam.comment")
require("nichtsam.gitsigns")
require("nichtsam.nvim-tree")
require("nichtsam.bufferline")
require("nichtsam.toggleterm")

-- In Organized Future it should look like:
-- require("nichtsam.fundamentals")
-- require("nichtsam.packer")
-- require("nichtsam.explore")
-- require("nichtsam.language")
-- require("nichtsam.editing")
-- require("nichtsam.integration")
